이메일 인증 재전송 기능 추가 및 비밀번호 변경 요청 핸들링 수정
somul-project/somul-system-backend pull request #8
Opened 2020-04-24 06:13 UTC by ehdgus8077

이메일 인증 재전송 기능 추가 및 비밀번호 변경 요청 핸들링 
수정하면서 유닛 테스트를 더 정밀하게 추가했습니다!

2020-04-28 09:25 UTC, harrydrippin commented
c1ed4a5 , 22cdb70 , 6329cc6 이름 앞에 태그가 누락되었습니다.

2020-04-28 09:27 UTC, harrydrippin requested changes

2020-04-28 09:27 UTC, harrydrippin commented on .env.sample
> +EXPOSE_API_DOCS = ""
파일 끝 개행이 빠져있습니다. Prettier를 돌리거나 VSCode 설정을 통해서 이를 자동화해주세요.

2020-04-28 09:29 UTC, harrydrippin commented
`master` 에 이미 있는 내용의 Commit들이 PR에 함께 포함되었습니다. 먼저 `master`에 대해 Rebase해주세요.

2020-05-18 07:50 UTC, harrydrippin requested changes

2020-05-18 07:50 UTC, harrydrippin commented on src/api/auth/authHandler.ts
> +      && (/^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*[A-Za-z!@#$%^&+=_]).{8,100}$/.test(password)))) {
Validation에 사용되는 정규식은 Config에 따로 분리되어 있으면 나중에 조건이 바뀔 때 검사하거나 변경할 때 쉽게 적용이 가능할 것 같아요.

2020-05-18 07:50 UTC, harrydrippin commented on src/api/auth/authHandler.ts
> +        await Slack.send('error', JSON.stringify(error));
이미 우리가 사용하는 CustomError Class가 있음에도 불구하고 `log.error`나 `Slack.send()`가 로직에서 직접 호출되는게 조금 이상한 것 같아요. 이 로직들은 CustomError 쪽으로 캡슐화되는게 맞지 않을까요?

2020-05-18 07:50 UTC, harrydrippin commented on src/api/graphql/resolver_handler/Library.ts
> +    await Slack.send('error', JSON.stringify(error));
위에도 말했지만, 계속 반복되는 거 같아서 에러 자체를 Custom하게 짜는 쪽으로 마이그레이션 하는게 좋을 거 같습니다.

2020-05-18 07:50 UTC, harrydrippin commented on src/common/error.ts
> +  notVerifyEmail = '112',
```suggestion
  emailNotVerified = '112',
```

2020-05-18 07:50 UTC, harrydrippin commented on src/server/server.ts
> +    this.app.listen(Number(constants.SERVER_PORT), '0.0.0.0',
이건 `Number()`로 강제 치환할 게 아니고, `parseInt(constants.SERVER_PORT, 10)` 처럼 해야 안전할 것 같습니다. `PORT`에 이상한 값이 들어갔다고 하면 에러가 나야할 거 같아요.

2020-05-23 07:22 UTC, dsa28s submitted a review, later dismissed

2020-05-23 07:22 UTC, dsa28s commented on Dockerfile
>  RUN npm install --only=prod
궁금한게 있어요!
항상 도커 이미지를 빌드하면, 2개가 만들어지던데 이유가 뭔가욤?

2020-05-23 07:22 UTC, dsa28s commented
@harrydrippin 일단 머지해줘!
백엔드 쪽도 이슈로 좀 관리했으면 좋겠답ㅠㅠ

2020-05-23 09:01 UTC, harrydrippin commented
일단 머지하겠습니다. 이건 일단 배포 과정에서 QA를 하는 것으로 하고, 제가 시간이 나는대로 리팩토링을 진행해보겠습니다.

2020-05-23 09:01 UTC, harrydrippin approved these changes

2020-05-23 09:01 UTC, merged